# Database connection settings
hibernate.connection.url=${DB_LINK_TEST}
hibernate.connection.username=${DB_USER}
hibernate.connection.password=${DB_PASSWORD}

# Echo all executed SQL to console
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true